services:
  django:
    build: ./PythonDocker
    container_name: contenedor_django
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./PythonDocker:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    build: ./MySQLDocker/
    container_name: mysql_db
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./MySQLDocker/conf:/etc/mysql/conf.d
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-proot", "-e", "SELECT 1"]
      timeout: 20s
      retries: 10
