# Generated by Django 5.1.4 on 2025-02-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('country_id', models.IntegerField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('device_id', models.IntegerField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'devices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entretaiment',
            fields=[
                ('entertainment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('entertainment_name', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'entretaiment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('gender_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'gender',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MediaGoal',
            fields=[
                ('goal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('goal_name', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'media_goal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Occupations',
            fields=[
                ('occupation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('occupation_name', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'occupations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('socialm_id', models.IntegerField(primary_key=True, serialize=False)),
                ('socialm_name', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'social_media',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('d_sm_time', models.FloatField()),
                ('d_entertain_time', models.FloatField()),
                ('sm_plat_used', models.IntegerField()),
                ('d_message_time', models.FloatField()),
                ('d_vid_cont_time', models.FloatField()),
                ('d_gaming_time', models.FloatField()),
                ('monthly_income', models.FloatField()),
                ('subscription_plats', models.IntegerField()),
                ('avg_sleep_time', models.FloatField()),
                ('physical_activity_tiem', models.FloatField()),
                ('reading_time', models.FloatField()),
                ('work_study_time', models.FloatField()),
                ('screen_time', models.FloatField()),
                ('d_num_notifications', models.IntegerField()),
                ('d_music_time', models.FloatField()),
                ('preferred_content_id', models.IntegerField()),
                ('online_comm_time', models.FloatField()),
                ('news_time', models.FloatField()),
                ('ad_interaction_count', models.IntegerField()),
                ('education_plat_time', models.FloatField()),
                ('tech_savviness_level', models.IntegerField()),
                ('sleep_quality', models.IntegerField()),
                ('monthly_spent_entertain', models.FloatField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
